version: 2
# root-markers:
#     - composer.json
tools:
    phpmd: &phpmd
        lint-command: 'vendor/binphpmd "${INPUT}" text .phpmd/phpmd.xml'
        lint-stdin: false
        lint-after-save: true
        lint-ignore-exit-code: true
        lint-formats:
            - '%f:%l%\t%m'
    php-phpstan: &php-phpstan
        lint-command: 'phpstan analyse --error-format raw --no-progress  -c phpstan.dist.neon'
languages:
    php:
        - <<: *php-phpstan
