# indent setting
set-option global tabstop 4
set-option global indentwidth 4

# change to space when input tab
hook global InsertChar \t %{
    exec -draft -itersel h@
}

# insert ; to end of line
# define-command add-semicolon-to-end %{;
#     execute-keys -draft 'gla;<esc>'
# };

# insert , to end of line
define-command add-comma-to-end %{;
    execute-keys -draft 'gla,<esc>'
};

map global user ';' ': add-semicolon-to-end<ret>'
map global user ',' ': add-comma-to-end<ret>'

# format the current buffer file by php-cs-fixer 
define-command php-cs-fix %{
    nop %sh{ php-cs-fixer fix "$kak_buffile" --quiet}
    edit!
}

# kak-tree-sitter:
# 公式の `eval %sh{ kak-tree-sitter -dks --init $kak_session }` は毎起動 ~150-300ms
# かかる(プロセス起動 + デーモンとのハンドシェイク)。出力はセッション非依存なので
# ~/.config/kak/cache/kak-tree-sitter.kak にキャッシュしておき、デーモン起動だけ
# バックグラウンドで投げる。バイナリ更新時は ~/.config/kak/refresh-cache.sh を実行。
source "%val{config}/cache/kak-tree-sitter.kak"
nop %sh{ kak-tree-sitter -ds >/dev/null 2>&1 & }

# transfer source code of rpst-v2 to remote server
define-command send-rpstv2 %{
    nop %sh{ transport_rpstv2.rb "$kak_bufname" > /dev/null 2>&1 &}
}


# remote serverでrpst-v2のテストを実行する
define-command v2test %{
    terminal sh -c "remote_phpunit_rpstv2.rb '%val{bufname}'; echo 'done';read"
    #nop %sh{
        #zellij run -- remote_phpunit_rpstv2.rb "$kak_bufname"
    #}
}

define-command pathcopy %{
    nop %sh{
        echo "$kak_bufname" | pbcopy
    }
}

# the command opening test runner in web browser
define-command open-testrunner -docstring "open rpst-x test runner in web browser" %{
    nop %sh{
        open 'https://tmorita-newrpst-dev74.precs.net/ci/cmd/sandbox/test_runner'
    }
}

define-command rubocop -docstring "format buffer with rubocop" %{
    execute-keys -draft '%|bundle exec rubocop --server --autocorrect --stdin "$kak_buffile" --stderr --fail-level error<ret>'
}
# transfer the buffer file to remote server automatically
hook global BufWritePost .*/ghq/github.com/PRECS-Inc/rpst-v2/.* %{
    send-rpstv2
}

# FZF
declare-user-mode fzf

define-command fzf-file -docstring 'search file by fzf' %{
    evaluate-commands %sh{
        dir=$(pwd)
        query_opt=""
        if [ "${#kak_selection}" -ge 2 ]; then
            query_opt="--query=\"$kak_selection\""
        fi
        cat <<EOF
        	terminal sh -c %{
            		preview='if command -v bat >/dev/null 2>&1; then bat --style=numbers --color=always --line-range=:200 {}; else cat {}; fi'
            		f=\$(cd "$dir" && (fd --type f 2>dev/null || find . -type f) | fzf $query_opt --preview "\$preview" --preview-window=right:60%:wrap) || exit 0
            		[ -z "\$f" ] && exit 0
            		printf 'evaluate-commands -try-client %s edit %%{%s/%s}\n' "$kak_client" "$dir" "\$f" | kak -p "$kak_session"
        	}
EOF
    }
}

define-command fzf-buffer -docstring 'search buffer by fzf' %{
    evaluate-commands %sh{
        cat <<EOF
        	terminal sh -c %{
        	        preview='if command -v bat >/dev/null 2>&1; then bat --style=numbers --color=always --line-range=:200 {}; else cat {}; fi'
        		f=\$(printf '%s\n' $kak_quoted_buflist | fzf --preview "\$preview") || exit 0;
        		[ -z "\$f"] && exit 0
        		printf "evaluate-commands -try-client '$kak_client' buffer '%s'" "\$f" | kak -p "$kak_session"
        	}
        EOF


    }
}
define-command fzf-grep -docstring 'grep by fzf' %{
    evaluate-commands %sh{
        dir=$(pwd)
        query_opt=""
        if [ "${#kak_selection}" -ge 2 ]; then
            query_opt="--query=\"$kak_selection\""
        fi
        cat <<EOF
        terminal sh -c %{
            # プレビュー: 該当行をハイライトし、その行へスクロールさせます（:200だと200行目以降の検索結果が見えないため）
            preview='if command -v bat >/dev/null 2>&1; then bat --style=numbers --color=always --highlight-line {2} {1}; else cat {1}; fi'
            
            # 修正1: 検索コマンドから --color=always を削除
            if command -v rg >/dev/null 2>&1; then
                search_cmd="rg --line-number --no-heading --hidden '^'"
            else
                search_cmd="grep -rnI --exclude-dir='.git' '^' . 2>/dev/null"
            fi

            # 修正2: プレビューウィンドウが該当行(+{2}-/2)を追従するように修正
            selected=\$(eval "\$search_cmd" | fzf $query_opt --delimiter : --preview "\$preview" --preview-window=right:60%:wrap:+{2}-/2) || exit 0

            [ -z "\$selected" ] && exit 0

            f=\$(printf '%s\n' "\$selected" | cut -d: -f1)
            line=\$(printf '%s\n' "\$selected" | cut -d: -f2)

            # 修正3: printf の %%s を %s に修正
            printf 'evaluate-commands -try-client %s edit %%{%s/%s} %s\n' "$kak_client" "$dir" "\$f" "\$line" | kak -p "$kak_session"
        }
EOF
    }
}

define-command fzf-git-files -docstring "grep git ls-files by fzf" %{
    evaluate-commands %sh{
        cat <<EOF
        terminal sh -c %{
    		preview='if command -v bat >/dev/null 2>&1; then bat --style=numbers --color=always --line-range=:200 {}; else cat {}; fi'
            selected=\$(git ls-files | fzf --preview "\$preview")
            if [ -n "\$selected" ]; then
                echo "evaluate-commands -try-client $kak_client edit %{\$selected}" | kak -p $kak_session   
            fi

        }
    }
}

define-command fzf-git-changes -docstring "grep git changed file by fzf" %{
    evaluate-commands %sh{
        cat <<EOF
        terminal sh -c %{
            preview='if command -v bat >/dev/null 2>&1; then bat --style=numbers --color=always {2} ; else cat {2}; fi'
            selected=\$(git status -s -uall | grep -v '/\$' | grep -E -v '^(D|.D)' | while IFS= read -r line; do
                filepath=\$(echo "\$line" | cut -c4-)
                if [ ! -d "\$filepath" ]; then
                    echo "\$line"
                fi
            done | fzf --preview "\$preview" | cut -c4-)

            if [ -n "\$selected" ]; then
                echo "evaluate-commands -try-client $kak_client edit %{\$selected}" | kak -p $kak_session
            fi
        }
EOF
    }
}

map global fzf f ': fzf-file<ret>' -docstring "file"
map global fzf b ': fzf-buffer<ret>' -docstring "buffer"
map global fzf g ': fzf-grep<ret>' -docstring "grep"
map global fzf p ': fzf-git-files<ret>' -docstring "git files"
map global fzf c ': fzf-git-changes<ret>' -docstring "git changes"
map global user f ':enter-user-mode fzf<ret>' -docstring "fzf..."

define-command yazi -docstring 'open yazi' %{
    evaluate-commands %sh{
        tmp=$(mktemp)
        # バッファがファイルと紐付いていない場合はカレントディレクトリをフォールバックに使う
        dir=$(dirname "$kak_buffile")
        [ -z "$dir" ] && dir=$PWD

        # ここで $kak_client と $kak_session を展開して、確実にターミナルへ渡す
        cat <<EOF
        terminal sh -c %{
            yazi "$dir" --chooser-file="$tmp"
            if [ -s "$tmp" ]; then
                while IFS= read -r f || [ -n "\$f" ]; do
                    [ -z "\$f" ] && continue
                    printf "evaluate-commands -try-client '%s' edit %%{%s}\n" "$kak_client" "\$f"
                done < "$tmp" | kak -p "$kak_session"
            fi
            rm -f "$tmp"
        }
EOF
    }
}
map global user e ': yazi<ret>' -docstring 'open yazi'
# ---- Plugins (direct source, plug.kak only loaded on-demand) ----
# plug.kak の起動時スキャンを避けるため、使うプラグインを直接 source する。
# install/update したいときだけ :plug-init で plug.kak をロード。
define-command plug-init -docstring 'Load plug.kak on demand for install/update commands' %{
    source "%val{config}/plugins/plug.kak/rc/plug.kak"
}

# auto-pairs
source "%val{config}/plugins/auto-pairs.kak/rc/auto-pairs.kak"
enable-auto-pairs

# smarttab
source "%val{config}/plugins/smarttab.kak/rc/smarttab.kak"

# kakoune-find
source "%val{config}/plugins/kakoune-find/find.kak"

# colorscheme (tokyonight)
# source "%val{config}/plugins/tokyonight.kak/colors/tokyonight.kak"
# colorscheme tokyonight

# git mode
source "%val{config}/plugins/kakoune-git-mode/git-mode.kak"
declare-git-mode
map global user g ': enter-user-mode git<ret>' -docstring "git mode"

# git gutter
source "%val{config}/plugins/simple-git-gutter.kak/git_gutter.kak"

hook global BufCreate .*\.html\.erb %{
    set-option buffer filetype erb
}

hook global BufCreate .*\.tpl %{
    set-option buffer filetype smarty
}

# kakoune-lsp: セッション非依存出力を cache から読み込む。
# バイナリ更新時は ~/.config/kak/refresh-cache.sh を実行すること。
source "%val{config}/cache/kak-lsp.kak"

set-option global lsp_snippet_support false

map global user l ':enter-user-mode lsp<ret>' -docstring "LSP Mode"
map global goto d <esc>:lsp-definition<ret> -docstring "LSP definition"
map global goto r <esc>:lsp-references<ret> -docstring "LSP references"
map global goto i <esc>:lsp-implementation<ret> -docstring "LSP implementation"
map global goto y <esc>:lsp-type-definition<ret> -docstring "LSP type definition"
map global user a <esc>:lsp-code-actions<ret> -docstring 'LSP code actions'
map global user R <esc>:lsp-rename-prompt<ret> -docstring 'LSP rename'
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP error and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP error'

hook global WinSetOption filetype=(php|go|ruby|typescript|erb|smarty|sql) %{
    lsp-enable-window
}

source "%val{config}/sqls.kak"

# erb / smarty は kak-lsp 標準の filetype フックがないので自前で lsp_servers を設定。
# kak-lsp 標準のフックは BufSetOption だが、これらは WinSetOption でも問題なく機能する。
hook global BufSetOption filetype=erb %{
    set-option buffer lsp_servers %{
        [herb]
        command = "herb-language-server"
        args = ["--stdio"]
        root_globs = ["Gemfile", ".git"]
    }
}

hook global BufSetOption filetype=smarty %{
    set-option buffer lsp_servers %{
        [html]
        command = "vscode-html-language-server"
        args = ["--stdio"]
        root_globs = [".git"]
        [html.settings.html.format]
        enable = false
    }
}


map global normal '#' :comment-line<ret>
map global user y '<a-|>pbcopy<ret>' -docstring "yank to clipboard"
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching
add-highlighter global/ dynregex '%reg{/}' 0:+bu
add-highlighter global/ column 80 default,rgb:303030
declare-option -hidden str lsp_modeline ""
set-option global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'
set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"


#--- 補完候補の選択remap
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n> -docstring "next completion"
    map window insert <s-tab> <c-p> -docstring "prev completion"
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

declare-user-mode window
map global normal <c-w> ':enter-user-mode window<ret>'
map global window  v ': tmux-terminal-horizontal kak -c %val{session}<ret>'
map global window  s ': tmux-terminal-vertical kak -c %val{session}<ret>'

# for erb highlighting
hook global WinSetOption filetype=erb %{
    require-module html
    require-module ruby

    add-highlighter window/erb regions
    add-highlighter window/erb/html default-region ref html
    add-highlighter window/erb/html region '<%[=#-]?' '-?>' ref ruby

    hook -once -always window WinSetOption filetype=.* %{
        remove-highlighter window/erb
    }
}

# for rpst smarty highlighting
hook global WinSetOption filetype=smarty %{
    require-module html

    add-highlighter window/smarty regions
    add-highlighter window/smarty/html default-region ref html
    add-highlighter window/smarty/eccube region '<!--\{' '\}-->' group

    add-highlighter window/smarty/eccube/ regex '\$[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*' 0:variable
    add-highlighter window/smarty/eccube/ regex '\b(if|else|elseif|foreach|from|item|key|name|include|assign|capture)\b' 0:keyword
    add-highlighter window/smarty/eccube/ regex '\|[a-zA-Z_]+' 0:function

    hook -once -always window WinSetOption filetype=.* %{
        remove-highlighter window/smarty
    }
}

evaluate-commands %sh{ hop-kak --init}
declare-option str hop_kak_keyset 'abcdefghijklmnopqrstuvwxyz'
map global normal <a-%> ':execute-keys gtGbx<ret>'
define-command hop-kak %{
    map global normal e ':eval -no-hooks -- %sh{hop-kak --keyset "$kak_opt_hop_kak_keyset " --sels "$kak_selections_desc" }<ret>'
}
define-command -override hop-kak-words %{
    exec 'gtGbxs\w+<ret>:eval -no-hooks -- %sh{hop-kak --keyset "$kak_opt_hop_kak_keyset " --sels "$kak_selections_desc" }<ret>'
}
map global user h :hop-kak-words<ret>
