# format the current buffer file by php-cs-fixer 
define-command php-cs-fix %{
    nop %sh{ php-cs-fixer fix "$kak_buffile" --quiet}
    edit!
}

# transfer source code of rpst-v2 to remote server
define-command send-rpstv2 %{
    nop %sh{ transport_rpstv2.rb "$kak_bufname" > /dev/null 2>&1 &}
}


# remote serverでrpst-v2のテストを実行する
define-command v2test %{
    terminal sh -c "remote_phpunit_rpstv2.rb '%val{bufname}'; echo 'done';read"
    #nop %sh{
        #zellij run -- remote_phpunit_rpstv2.rb "$kak_bufname"
    #}
}

define-command pathcopy %{
    nop %sh{
        echo "$kak_bufname" | pbcopy
    }
}

# the command opening test runner in web browser
define-command open-testrunner -docstring "open rpst-x test runner in web browser" %{
    nop %sh{
        open 'https://tmorita-newrpst-dev74.precs.net/ci/cmd/sandbox/test_runner'
    }
}

define-command rubocop -docstring "format buffer with rubocop" %{
    execute-keys -draft '%|bundle exec rubocop --server --autocorrect --stdin "$kak_buffile" --stderr --fail-level error<ret>'
}
# transfer the buffer file to remote server automatically
hook global BufWritePost .*/ghq/github.com/PRECS-Inc/rpst-v2/.* %{
    send-rpstv2
}

# FZF
declare-user-mode fzf

define-command fzf-file -docstring 'search file by fzf' %{
    evaluate-commands %sh{
        dir=$(pwd)
        cat <<EOF
        	terminal sh -c %{
            		preview='if command -v bat >/dev/null 2>&1; then bat --style=numbers --color=always --line-range=:200 {}; else cat {}; fi'
            		f=\$(cd "$dir" && (fd --type f 2>dev/null || find . -type f) | fzf --preview "\$preview" --preview-window=right:60%:wrap) || exit 0
            		[ -z "\$f"] && exit 0
            		printf 'evaluate-commands -try-client %s edit %%{%s/%s}\n' "$kak_client" "$dir" "\$f" | kak -p "$kak_session"
        	}

    }
}

define-command fzf-buffer -docstring 'search buffer by fzf' %{
    evaluate-commands %sh{
        cat <<EOF
        	terminal sh -c %{
            		preview='if command -v bat >/dev/null 2>&1; then bat --style=numbers --color=always --line-range=:200 {}; else cat {}; fi'
            		f=\$(printf '%s\n' "$kak_quoted_buflist" | xargs -n 1 | fzf --preview "\$preview" ) || exit 0
            		[ -z "\$f"] && exit 0
            		printf 'evaluate-commands -try-client %s edit %%{%s/%s}\n' "$kak_client" "$dir" "\$f" | kak -p "$kak_session"
        	}
        EOF


    }
}

map global fzf f ': fzf-file<ret>' -docstring "file"
map global fzf b ': fzf-buffer<ret>' -docstring "buffer"
map global user f ':enter-user-mode fzf<ret>' -docstring "fzf..."

# open yazi as a file manager
define-command yazi -docstring 'open yazi in current buffer dir' %{
    evaluate-commands %sh{
        tmp=$(mktemp)
        dir=$(dirname "$kak_buffile")
        cat <<EOF
terminal sh -c %{
    yazi "$dir" --chooser-file="$tmp"
    if [ -s "$tmp" ]; then
        while IFS= read -r f || [ -n "\$f" ]; do
            [ -z "\$f" ] && continue
            printf 'evaluate-commands -try-client %s edit %%{%s}\n' "$kak_client" "\$f"
        done < "$tmp" | kak -p "$kak_session"
    fi
    rm -f "$tmp"
}
EOF
    }
}
map global user e ': yazi<ret>' -docstring 'open yazi'
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug 'andreyorst/plug.kak' noload
plug 'alexherbo2/auto-pairs.kak' config %{
    enable-auto-pairs
}

plug 'andreyorst/smarttab.kak'
plug 'occivink/kakoune-find'
plug "andreyorst/base16-gruvbox.kak" theme config %{
    # colorscheme base16-gruvbox-dark-medium
}
plug "taro0079/tokyonight.kak" theme config %{
    # colorscheme tokyonight
}
plug 'jordan-yee/kakoune-git-mode' config %{
    declare-git-mode
    map global user g ': enter-user-mode git<ret>' -docstring "git mode"
}

# plug "andreyorst/fzf.kak" config %{
    # map -docstring 'fzf mode' global normal '<c-p>' ': fzf-mode<ret>'
# }

plug "tom-huntington/simple-git-gutter.kak"

hook global BufCreate .*\.html\.erb %{
    set-option buffer filetype erb
}

plug "kak-lsp/kak-lsp" noload config %{
    eval %sh{kak-lsp}
    hook global WinSetOption filetype=(php|go|ruby|typescript) %{
        lsp-enable-window
    }

    hook global WinSetOption filetype=erb %{
        set-option buffer lsp_servers %{
            [herb]
            command = "herb-language-server"
            args = ["--stdio"]
            root_globs = ["Gemfile", ".git"]

            [herb.settings]

        }
        lsp-enable-window
    }

    map global user l ':enter-user-mode lsp<ret>' -docstring "LSP Mode"
    map global goto d <esc>:lsp-definition<ret> -docstring "LSP definition"
    map global goto r <esc>:lsp-references<ret> -docstring "LSP references"
    map global goto i <esc>:lsp-implementation<ret> -docstring "LSP implementation"
    map global goto y <esc>:lsp-type-definition<ret> -docstring "LSP type definition"

    map global user a <esc>:lsp-code-actions<ret> -docstring 'LSP code actions'
    map global user R <esc>:lsp-rename-prompt<ret> -docstring 'LSP rename'

    map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>'

    map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
    map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
    map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
    map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
    map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP error and warnings'
    map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP error'

}

map global normal '#' :comment-line<ret>
map global user y '<a-|>pbcopy<ret>' -docstring "yank to clipboard"
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ show-matching
add-highlighter global/ dynregex '%reg{/}' 0:+bu
add-highlighter global/ column 80 default,rgb:303030
set-option global modelinefmt '%val{bufname} %val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'
set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"


#--- 補完候補の選択remap
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n> -docstring "next completion"
    map window insert <s-tab> <c-p> -docstring "prev completion"
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

hook global BufCreate .*\.(tpl) %{ set buffer filetype html }
declare-user-mode window
map global normal <c-w> ':enter-user-mode window<ret>'
map global window  v ': tmux-terminal-horizontal kak -c %val{session}<ret>'
map global window  s ': tmux-terminal-vertical kak -c %val{session}<ret>'

# for erb highlighting
hook global WinSetOption filetype=erb %{
    require-module html
    require-module ruby

    add-highlighter window/erb regions
    add-highlighter window/erb/html default-region ref html
    add-highlighter window/erb/html region '<%[=#-]?' '-?>' ref ruby

    hook -once -always window WinSetOption filetype=.* %{
        remove-highlighter window/erb
    }
}
